---
Resources:
  exampleTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stage}-example-table
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      Tags:
        -
          Key: Name
          Value: ${self:provider.stage}-example-table
        -
          Key: Environment
          Value: ${self:provider.stage}
