#TODO: Update the development environment specific configuration here
# AWS
aws:
  # aws-cli profile
  profile: development-profile
  # VPC configuration
  vpc:
    securityGroupIds:
      - dummy-group
    subnetIds:
      - dummy-subnet-1
      - dummy-subnet-2

# serverless deployment bucket
serverless:
  deploymentBucket: dummy-bucket

# Debug log enabled
debug:
  enabled: true
